---
galaxy_info:
  author: Andrey Kislyak
  description: Role installs and configure nginx.
  license: Apache
  min_ansible_version: 2.6
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []

dependencies: []
