---
# tasks file for dj-wasabi.zabbix-proxy

- name: "Set OS dependent variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/main.yml"

- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Debian.yml"
  when:
    - ansible_os_family == "Debian"

- name: "Installing the database"
  include: "{{ zabbix_proxy_database_long }}.yml"

- name: "Create include dir zabbix-proxy"
  file:
    path: "{{ zabbix_proxy_include }}"
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory
  become: yes

- name: "Create module dir zabbix-proxy"
  file:
    path: "{{ zabbix_proxy_loadmodulepath }}"
    owner: zabbix
    group: zabbix
    state: directory
  become: yes

- name: "Create directory for PSK file if not exist."
  file:
    path: "{{ zabbix_proxy_tlspskfile | dirname }}"
    mode: 0755
    state: directory
  become: yes
  when:
    - zabbix_proxy_tlspskfile is defined

- name: "Place TLS PSK File"
  copy:
    dest: "{{ zabbix_proxy_tlspskfile }}"
    content: "{{ zabbix_proxy_tlspsk_secret }}"
    owner: zabbix
    group: zabbix
    mode: 0400
  become: yes
  when:
    - zabbix_proxy_tlspskfile is defined
    - zabbix_proxy_tlspsk_secret is defined
  notify:
    - restart zabbix-proxy

- name: "Allow zabbix-proxy to open connections (SELinux)"
  seboolean:
    name: zabbix_can_network
    persistent: yes
    state: yes
  become: yes
  when: ansible_selinux.status == "enabled"
  tags: selinux

- name: "Allow zabbix-proxy to connect to zabbix_proxy_preprocessing.sock (SELinux)"
  seboolean:
    name: daemons_enable_cluster_mode
    persistent: yes
    state: yes
  become: yes
  when: ansible_selinux.status == "enabled"
  tags: selinux

- name: "Configure zabbix-proxy"
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-proxy

- name: Create a new proxy or update an existing proxy
  zabbix_proxy:
    server_url: "{{ zabbix_url }}"
    http_login_user: "{{ zabbix_api_http_user | default(omit) }}"
    http_login_password: "{{ zabbix_api_http_password | default(omit) }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    proxy_name: "{{ zabbix_proxy_hostname }}"
    status: "{{ zabbix_proxy_status }}"
    interfaces: "{{ zabbix_proxy_interface | default(omit) }}"
    description: "{{ zabbix_proxy_description }}"
    state: present
  when:
    - zabbix_api_create_hosts | bool
  register: zabbix_api_host_created
  until: zabbix_api_host_created is succeeded
  delegate_to: "{{ zabbix_proxy_delegate_admin_to }}"
  become: no
  changed_when: false
  tags:
    - api


- name: "zabbix-proxy started"
  service:
    name: zabbix-proxy
    state: started
    enabled: yes
  become: yes
