---
nginx_only_sites_from_http_template: True
nginx_http_template:
  zabbix:
    template_file: zabbix_site.conf.j2
    listen: 80
    server_name: "zabbix.bankofpartners.com"
    root: /usr/share/zabbix
    php_socket: /var/run/php_zabbix.sock

php_version: 72
php_packages:
- "php{{ php_version }}"
- "php{{ php_version }}-php-common"
- "php{{ php_version }}-php-json"
- "php{{ php_version }}-php-pgsql"
- "php{{ php_version }}-php-mbstring"
- "php{{ php_version }}-php-bcmath"
- "php{{ php_version }}-php-xml"
- "php{{ php_version }}-php-gd"
- "php{{ php_version }}-runtime"
- "php{{ php_version }}-php-pdo"
- "php{{ php_version }}-php-cli"
- "php{{ php_version }}-php-fpm"

php_fpm_pools:
  zabbix:
    template_file: php_fpm_www.conf.j2
    prefix: '/usr/share/zabbix'
    user: apache
    group: apache
    listen:
      address: '/var/run/php_zabbix.sock'
      allowed_clients: '127.0.0.1'
      owner: nginx
      group: nginx
    pm:
      type: dynamic
      max_children: 50
      start_servers: 5
      min_spare_servers: 5
      max_spare_servers: 35
    slowlog: "/var/opt/remi/php{{ php_version }}/log/php-fpm/www-slow.log"
    php_admin_value:
      error_log: "/var/opt/remi/php{{ php_version }}/log/php-fpm/www-error.log"
    php_admin_flag:
      log_errors: 'on'
    php_value:
      'session.save_handler': files
      'session.save_path': "/var/opt/remi/php{{ php_version }}/lib/php/session"
      max_execution_time: 300
      memory_limit: 128M
      post_max_size: 16M
      upload_max_filesize: 2M
      max_input_time: 300
      max_input_vars: 10000
      'date.timezone': "Europe/Moscow"


postgresql_admin_user: "postgres"
postgresql_cluster_name: "main"

postgresql_ext_install_contrib: true
postgresql_listen_addresses: ['localhost']
postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5"}
postgresql_users:
  - name: "{{ zabbix_server_dbuser }}"
    pass: "{{ zabbix_server_dbpassword }}"
postgresql_databases:
  - name:  "{{ zabbix_server_dbname }}"
    owner: "{{ zabbix_server_dbuser }}"
postgresql_user_privileges:
  - name: "{{ zabbix_server_dbuser }}"
    db: "{{ zabbix_server_dbname }}"
    priv: "ALL"

zabbix_proxy: ""
zabbix_link_templates:
  - Template OS Linux by Zabbix agent
  - Template App Zabbix Server
  - 'basic_metrics'
  - 'Nginx'
