---

postgresql_admin_user: "postgres"
postgresql_cluster_name: "main"

postgresql_ext_install_contrib: true
postgresql_listen_addresses: ['localhost']
postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5"}
postgresql_users:
  - name: "{{ zabbix_proxy_dbuser }}"
    pass: "{{ zabbix_proxy_dbpassword }}"
postgresql_databases:
  - name:  "{{ zabbix_proxy_dbname }}"
    owner: "{{ zabbix_proxy_dbuser }}"
postgresql_user_privileges:
  - name: "{{ zabbix_proxy_dbuser }}"
    db: "{{ zabbix_proxy_dbname }}"
    priv: "ALL"

zabbix_link_templates:
  - Template OS Linux by Zabbix agent
  - Template App Zabbix Proxy
